import { BrandbookData } from "./types";

// Auto-generated by scripts/gen-caraca-ts.mjs
// Inlined as TypeScript object to avoid webpack JSON.parse bundling issue in production.
// Do NOT edit manually — edit caraca-bar-brandbook.json and re-run the script.
export const caracaBarExample = {
  "schemaVersion": "2.0",
  "brandName": "Caraca! Bar",
  "industry": "Bar & Gastronomia — Boteco Tropical de Encontro",
  "brandConcept": {
    "purpose": "Transformar a mesa de bar em um ponto de encontro brasileiro cheio de humor, sabor e identidade viva — um lugar onde as pessoas comem bem, brindam melhor e saem dizendo 'caraca!'.",
    "mission": "Servir porções, drinks, lanches e pratos em um ambiente caloroso que mistura brasilidade, irreverência e presença visual memorável sem perder a alma popular do bar.",
    "vision": "Ser a marca de bar mais reconhecível e querida de Londrina quando alguém quiser reunir amigos, comer bem e viver uma experiência brasileira sem pose, mas com assinatura.",
    "uniqueValueProposition": "Caraca! Bar combina atmosfera real de encontro, linguagem popular brasileira, identidade verde-amarela imediatamente reconhecível e um repertório visual tropical mais autoral — fazendo a marca parecer viva no feed, na fachada, no balcão e na memória.",
    "reasonsToBelieve": [
      "Perfil @caracabaroficial com 22,4 mil seguidores, 347 posts e linguagem visual consistente nas peças públicas observadas",
      "Sistema atual já reconhecível em verde profundo + amarelo dourado, lettering gestual e ícones circulares nos highlights",
      "Mistura recorrente de gente real, ambiente, pratos, porções, burgers e drinks — a marca vive em operação, não só em conceito",
      "Endereço, fachada e bio reforçam ancoragem local e sensação de ponto de encontro de bairro com força de marca"
    ],
    "userPsychographics": "Adultos jovens e grupos de amigos que valorizam lugar com cara própria, comida boa sem afetação, humor brasileiro e ambiente em que dá vontade de voltar. Gostam de postar o que é genuíno, não o que parece montado demais.",
    "values": [
      "Calor Humano — a mesa como lugar de encontro, conversa e repetição de visita",
      "Brasilidade Cotidiana — falar e servir como quem conhece o gosto do público brasileiro de verdade",
      "Generosidade de Boteco — fartura percebida, acolhimento e informalidade bem resolvida",
      "Humor sem Afetação — comunicação divertida, popular e memorável sem virar caricatura",
      "Sistema com Assinatura — evoluir a identidade atual para algo mais coerente, reconhecível e aplicável"
    ],
    "personality": [
      "Caloroso e sociável",
      "Solar e brasileiro",
      "Popular bem resolvido",
      "Irreverente sem deboche",
      "Entusiasmado de forma genuína"
    ],
    "toneOfVoice": "Direto, caloroso e coloquial. Fala como quem convida para sentar, pedir uma porção e ficar mais um pouco. Usa humor brasileiro, frases promocionais com energia e entusiasmo real. Deve soar como marca viva de bar, não como restaurante formal nem como pub importado.",
    "brandArchetype": "Cara Comum + Criador — recebe todo mundo sem pose, mas transforma esse encontro em uma marca com assinatura visual própria, humor e repertório reconhecível."
  },
  "brandStory": {
    "manifesto": "Há bares que servem bebida. Há bares que servem comida. E há bares que servem aquele tipo de noite que você quer repetir. O Caraca! nasceu para ser isso: um ponto de encontro com cara própria, clima brasileiro e energia de quem gosta de ver a mesa cheia, a conversa rendendo e o copo voltando gelado.\n\nA gente acredita em brasilidade sem fantasia, em humor sem afetação e em design que aproxima em vez de afastar. O verde e o amarelo aqui não são enfeite: são presença. A comida não entra como cenário. O cliente não entra como figurante. Tudo existe para fazer o lugar viver de verdade — no bar, na rua e no feed.",
    "originStory": "O Caraca! consolidou sua força local combinando logo memorável, linguagem calorosa, fotos de produto e gente real, além de uma presença digital que faz o público reconhecer o bar antes mesmo de ler a legenda. Agora a evolução da marca parte dessa força já construída: manter a energia popular e o reconhecimento visual, mas organizar melhor o sistema para crescer com mais coerência.",
    "brandPromise": "Você vai sair do Caraca! com a sensação de que valeu a mesa, valeu a companhia e valeu voltar. Tudo deve reforçar isso — do primeiro story à última porção.",
    "brandBeliefs": [
      "Acreditamos que bar bom é o que vira ponto de encontro",
      "Acreditamos que comida boa e identidade forte podem coexistir sem frescura",
      "Acreditamos que o humor brasileiro aproxima mais do que qualquer texto sofisticado",
      "Acreditamos que uma marca de bar precisa aparecer viva em gente, produto e ambiente ao mesmo tempo",
      "Acreditamos que o 'Caraca!' é menos um truque gráfico e mais um estado emocional da marca"
    ]
  },
  "positioning": {
    "category": "Boteco Tropical Urbano de Encontro",
    "targetMarket": "Adultos de 23 a 40 anos, especialmente em Londrina e entorno, que escolhem bares por clima, companhia, variedade de consumo e personalidade visual — sem abrir mão de preço percebido justo e atmosfera real.",
    "positioningStatement": "Para quem procura um bar com comida boa, drinks marcantes, ambiente vivo e identidade própria, Caraca! Bar é o boteco tropical urbano que transforma encontro em marca — com humor brasileiro, presença visual reconhecível e sensação de lugar que já faz parte da rotina boa da cidade.",
    "primaryDifferentiators": [
      "Equity visual já existente em verde profundo, amarelo dourado, lettering gestual e ícones circulares nos destaques",
      "Conteúdo mistura clientes, pratos, porções, lanches, drinks e ambiente real — a marca parece vivida e não montada",
      "Tom promocional popular, caloroso e memorável, com frases que soam de bar brasileiro de verdade",
      "Potencial de evolução forte: transformar os códigos atuais em um sistema mais governado, tropical e autoral sem perder reconhecimento"
    ],
    "competitiveAlternatives": [
      "Bares genéricos com comunicação promocional sem assinatura",
      "Pubs e gastrobares de estética importada ou industrial",
      "Restaurantes visualmente bonitos, mas sem calor humano e sem linguagem de boteco"
    ],
    "reasonsToBelieve": [
      "22,4 mil seguidores e 347 posts no perfil observado, com recorrência clara de produto, clientes e ambiente",
      "Bio e endereço público reforçam ancoragem local: Rua Caracas, 166 — Londrina",
      "Highlights já organizam a marca em pilares concretos: Drinks, Clientes, Lanches, Pratos, Porções e Nosso bar"
    ]
  },
  "audiencePersonas": [
    {
      "name": "Ana Paula — A Organizadora do Rolê",
      "role": "Analista de marketing, 29 anos, Londrina",
      "context": "É quem escolhe o bar do grupo, compara ambiente, cardápio e clima antes de decidir. Gosta de lugar que renda stories, mas só volta quando a experiência é leve e gostosa de verdade.",
      "goals": [
        "Acertar um lugar que funcione para todo mundo",
        "Encontrar drinks e porções com boa apresentação",
        "Ter um bar com cara própria para repetir com frequência"
      ],
      "painPoints": [
        "Bares sem identidade visual e sem personalidade",
        "Lugares bonitos mas pouco acolhedores",
        "Comunicação de promoções confusa ou genérica"
      ],
      "objections": [
        "Será que é só mais um bar instagramável?",
        "A marca promete mais do que entrega na mesa?"
      ],
      "channels": [
        "Instagram",
        "Google Maps",
        "WhatsApp",
        "TikTok"
      ]
    },
    {
      "name": "Felipe — O Cliente de Repetição",
      "role": "Representante comercial, 34 anos, Londrina",
      "context": "Usa o bar como lugar de encontro no meio da semana e no fim de semana. Valoriza fartura, agilidade, clima informal e um cardápio que agrade o grupo inteiro.",
      "goals": [
        "Ter um ponto de encontro confiável",
        "Comer bem sem cerimônia",
        "Levar amigos para um lugar com personalidade e bom astral"
      ],
      "painPoints": [
        "Bares com atendimento frio",
        "Porções pequenas demais para o preço",
        "Ambientes sem energia social"
      ],
      "objections": [
        "Se for moderno demais, pode ter perdido a alma do bar",
        "Se a comunicação for exagerada, talvez a entrega não acompanhe"
      ],
      "channels": [
        "Instagram",
        "Boca a boca",
        "WhatsApp",
        "Google Maps"
      ]
    },
    {
      "name": "Luiza — A Criadora Local de Conteúdo",
      "role": "Estudante e microinfluenciadora, 24 anos, Londrina",
      "context": "Procura lugares visualmente reconhecíveis, com fotos boas de produto, humor na comunicação e ambiente que gere conteúdo orgânico sem parecer forçado.",
      "goals": [
        "Encontrar marca com linguagem própria",
        "Postar conteúdo de comida e drinks com cara de descoberta",
        "Associar sua imagem a lugares que pareçam vivos e atuais"
      ],
      "painPoints": [
        "Feed poluído demais",
        "Estética copiada de outros bares",
        "Artes promocionais sem assinatura"
      ],
      "objections": [
        "Se tudo for só promoção, a marca perde charme",
        "Se faltar consistência visual, o conteúdo não rende memória"
      ],
      "channels": [
        "Instagram",
        "TikTok",
        "Reels",
        "Stories"
      ]
    }
  ],
  "verbalIdentity": {
    "tagline": "há bares que vêm pro bem.",
    "oneLiner": "Caraca! Bar é o boteco tropical urbano onde porção, drink, humor e encontro ganham uma marca que o público reconhece de longe e lembra depois.",
    "brandVoiceTraits": [
      "Caloroso",
      "Popular bem resolvido",
      "Bem-humorado",
      "Promocional com personalidade",
      "Brasileiro"
    ],
    "messagingPillars": [
      {
        "title": "Bar que vive na rotina boa da cidade",
        "description": "O Caraca! se posiciona como lugar de encontro recorrente, não como experiência rara ou elitizada.",
        "proofPoints": [
          "Fachada reconhecível",
          "Bio com endereço explícito",
          "Conteúdo recorrente de clientes e ambiente"
        ],
        "exampleCopy": [
          "Tem lugar que você visita. O Caraca! é lugar que entra no teu roteiro.",
          "Chama a turma. O resto a gente põe na mesa."
        ]
      },
      {
        "title": "Comida e drink com energia de verdade",
        "description": "A marca precisa parecer saborosa, generosa e viva. Produto nunca entra como detalhe secundário.",
        "proofPoints": [
          "Posts de pratos, lanches, porções e drinks aparecem como protagonistas",
          "Close real de comida",
          "Combinação de oferta e desejo nas artes promocionais"
        ],
        "exampleCopy": [
          "Rodízio de espetos e porções pra resolver tua noite sem enrolação.",
          "Essa caipirinha não pede legenda grande. Pede replay."
        ]
      },
      {
        "title": "Humor brasileiro sem caricatura",
        "description": "A comunicação pode brincar, exagerar com afeto e usar expressões populares, desde que continue parecendo marca real de bar.",
        "proofPoints": [
          "Nome exclamativo já carrega energia",
          "Chamadas promocionais observadas usam humor curto e direto",
          "A linguagem não depende de formalidade para parecer profissional"
        ],
        "exampleCopy": [
          "Bom pra cacildsii.",
          "Caraca, olha isso aqui e me diz se tu não vinha."
        ]
      }
    ],
    "vocabulary": {
      "preferred": [
        "caraca",
        "porções",
        "drinks",
        "lanches",
        "pratos",
        "nosso bar",
        "vem pro bem",
        "bora",
        "mesa",
        "rolê",
        "gelado",
        "fartura"
      ],
      "avoid": [
        "gourmet",
        "sofisticação autoral",
        "alta gastronomia",
        "mixologia exclusiva",
        "experiência premium",
        "craft",
        "fine dining",
        "signature drinks"
      ]
    },
    "doDont": {
      "do": [
        "Usar frases curtas e convidativas",
        "Parecer gente chamando gente",
        "Nomear produtos e momentos com clareza",
        "Usar humor como tempero, não como muleta"
      ],
      "dont": [
        "Não soar corporativo",
        "Não escrever como pub importado",
        "Não exagerar em adjetivos vazios",
        "Não transformar toda peça em panfleto gritante"
      ]
    },
    "sampleHeadlines": [
      "Há bares que vêm pro bem.",
      "Caraca, olha esse drink.",
      "Teu novo ponto de encontro já tem endereço.",
      "Porção na mesa. Conversa rendendo. Do jeito que tem que ser.",
      "Drinks, clientes, lanches, pratos e vontade de voltar."
    ],
    "sampleCTAs": [
      "Chama a turma",
      "Ver cardápio",
      "Reservar mesa",
      "Pedir agora",
      "Ver nosso bar"
    ],
    "tonePerChannel": [
      {
        "channel": "Instagram",
        "tone": "Visual, direto e caloroso. O texto complementa a imagem sem disputar com ela.",
        "example": "Caraca, essa aqui é daquelas que resolve o fim do dia em dois goles e uma mesa cheia. #caracabar #vemprobem"
      },
      {
        "channel": "WhatsApp",
        "tone": "Próximo, rápido e resolutivo. Parece mensagem de quem está te esperando no bar.",
        "example": "Oi! Hoje tem rodízio e mesa boa te esperando. Quer que eu já confirme tua reserva?"
      },
      {
        "channel": "Site",
        "tone": "Informativo com clima. Explica o essencial sem perder o calor da marca.",
        "example": "Rua Caracas, 166. Vem pelo drink, fica pelo encontro e volta porque o clima pede."
      },
      {
        "channel": "Atendimento",
        "tone": "Humano, educado e sem script engessado.",
        "example": "Poxa, valeu por avisar. Vamos resolver isso agora pra tua experiência ficar redonda."
      },
      {
        "channel": "TikTok",
        "tone": "Espontâneo, divertido e mais cru que o Instagram. Mostra bastidor, reação e comida sem polimento excessivo.",
        "example": "POV: tu pediu só uma porção e saiu montando mesa pra noite inteira."
      }
    ]
  },
  "logo": {
    "primary": "https://placehold.co/800x300/006B60/D5A41D?text=Caraca!+Bar",
    "secondary": "https://placehold.co/400x200/D5A41D/006B60?text=Caraca!+Bar",
    "symbol": "https://placehold.co/400x400/006B60/D5A41D?text=C!",
    "favicon": "Selo circular verde com assinatura gestual amarela. Em microescala, usar a curva inicial do lettering com ponto de exclamação simplificado.",
    "clearSpace": "A forma-base do sistema é um selo circular/oval com assinatura caligráfica viva dentro dele. O respiro mínimo deve equivaler à altura do 'B' de 'Bar' ao redor do conjunto. O ponto de exclamação continua parte do nome, mas não precisa virar símbolo autônomo em toda peça; ele entra quando reforça energia e reconhecimento.",
    "minimumSize": "Digital: 96px de largura para wordmark completo. Impresso: 24mm. Ícone circular: 16px em digital e 8mm em impressão.",
    "incorrectUsages": [
      "Nunca trocar a relação verde + amarelo por combinações aleatórias",
      "Nunca distorcer o lettering para parecer fonte digitada comum",
      "Nunca forçar o ponto de exclamação como ícone isolado se isso prejudicar legibilidade",
      "Nunca remover o contorno/área de proteção do selo quando o fundo for fotográfico complexo",
      "Nunca aplicar sombras, brilhos, bevel, neon ou efeitos 3D",
      "Nunca usar o logo como se fosse marca de pub inglês ou beer house importado"
    ],
    "semioticAnalysis": {
      "natureOfSymbol": "Index",
      "denotation": "Assinatura gestual amarela acomodada dentro de um campo circular verde",
      "connotation": "Sinal de presença, espontaneidade e encontro. Parece marca que já está viva na rua, no copo e no feed — não marca conceitual distante do público"
    },
    "shapePsychology": "O círculo do selo comunica encontro, mesa, comunidade e recorrência. O gesto caligráfico injeta calor humano, informalidade e energia popular brasileira.",
    "negativeSpaceMetaphor": "O vazio dentro do selo funciona como palco para o gesto do nome. O campo verde concentra atenção e transforma o lettering em assinatura instantânea.",
    "evolutionaryStage": "Transitional"
  },
  "logoVariants": {
    "horizontal": "https://placehold.co/900x240/006B60/D5A41D?text=Caraca!+Bar",
    "stacked": "https://placehold.co/400x400/006B60/D5A41D?text=Caraca!%0ABar",
    "mono": "https://placehold.co/700x220/FFFFFF/0E4038?text=Caraca!+Bar",
    "negative": "https://placehold.co/700x220/0E4038/F4E6A7?text=Caraca!+Bar",
    "markOnly": "https://placehold.co/300x300/006B60/D5A41D?text=C!",
    "wordmarkOnly": "https://placehold.co/700x180/F4EFE3/006B60?text=Caraca!+Bar"
  },
  "colors": {
    "primary": [
      {
        "name": "Verde Caraca — presença principal do selo e da fachada",
        "hex": "#006B60",
        "rgb": "0, 107, 96",
        "cmyk": "100, 28, 56, 21",
        "pantone": "Pantone (verificar com Pantone Color Bridge)",
        "usage": "Cor estrutural do logo, fundos institucionais, destaques de sinalização e base dos ícones circulares.",
        "tonalScale": [
          {
            "shade": "50",
            "hex": "#E6F3F1"
          },
          {
            "shade": "100",
            "hex": "#C0E2DD"
          },
          {
            "shade": "200",
            "hex": "#99D1C9"
          },
          {
            "shade": "300",
            "hex": "#66B8AE"
          },
          {
            "shade": "500",
            "hex": "#006B60"
          },
          {
            "shade": "700",
            "hex": "#005349"
          },
          {
            "shade": "900",
            "hex": "#0E4038"
          }
        ]
      },
      {
        "name": "Amarelo Surpresa — energia solar do lettering",
        "hex": "#D5A41D",
        "rgb": "213, 164, 29",
        "cmyk": "10, 34, 96, 7",
        "pantone": "Pantone (verificar com Pantone Color Bridge)",
        "usage": "Lettering, ícones de destaque, chamadas promocionais e pontos de calor sobre fundos verdes ou escuros.",
        "tonalScale": [
          {
            "shade": "50",
            "hex": "#FBF4DD"
          },
          {
            "shade": "100",
            "hex": "#F5E9B8"
          },
          {
            "shade": "200",
            "hex": "#F0DF93"
          },
          {
            "shade": "300",
            "hex": "#E8CD5E"
          },
          {
            "shade": "500",
            "hex": "#D5A41D"
          },
          {
            "shade": "700",
            "hex": "#A37C10"
          },
          {
            "shade": "900",
            "hex": "#6F540A"
          }
        ]
      }
    ],
    "secondary": [
      {
        "name": "Areia de Guardanapo — base clara para respiro e papelaria",
        "hex": "#E8D5B5",
        "rgb": "232, 213, 181",
        "cmyk": "8, 13, 27, 0",
        "pantone": "Pantone (verificar com Pantone Color Bridge)",
        "usage": "Fundos claros, caixas de texto, cardápio, materiais impressos e áreas de respiro do sistema.",
        "tonalScale": [
          {
            "shade": "50",
            "hex": "#FAF6EE"
          },
          {
            "shade": "100",
            "hex": "#F5EEDF"
          },
          {
            "shade": "200",
            "hex": "#EFE4CE"
          },
          {
            "shade": "300",
            "hex": "#E8D5B5"
          },
          {
            "shade": "500",
            "hex": "#D9BD8E"
          },
          {
            "shade": "700",
            "hex": "#B28E58"
          },
          {
            "shade": "900",
            "hex": "#7C6036"
          }
        ]
      },
      {
        "name": "Terracota Petisco — calor de fritura, brick e madeira",
        "hex": "#A85A31",
        "rgb": "168, 90, 49",
        "cmyk": "20, 66, 83, 10",
        "pantone": "Pantone (verificar com Pantone Color Bridge)",
        "usage": "Acentos quentes em promoções, preços, detalhes gastronômicos e apoio cromático em fotos.",
        "tonalScale": [
          {
            "shade": "50",
            "hex": "#F6E8E0"
          },
          {
            "shade": "100",
            "hex": "#EBCDBE"
          },
          {
            "shade": "200",
            "hex": "#E0B19C"
          },
          {
            "shade": "300",
            "hex": "#C98260"
          },
          {
            "shade": "500",
            "hex": "#A85A31"
          },
          {
            "shade": "700",
            "hex": "#7F3F20"
          },
          {
            "shade": "900",
            "hex": "#572914"
          }
        ]
      },
      {
        "name": "Folha de Varanda — verde vivo para apoio tropical",
        "hex": "#2F8A72",
        "rgb": "47, 138, 114",
        "cmyk": "82, 23, 57, 7",
        "pantone": "Pantone (verificar com Pantone Color Bridge)",
        "usage": "Folhagens, cantos botânicos, ilustrações e sobreposições de natureza controlada.",
        "tonalScale": [
          {
            "shade": "50",
            "hex": "#E9F5F1"
          },
          {
            "shade": "100",
            "hex": "#C9E8DE"
          },
          {
            "shade": "200",
            "hex": "#A8DACB"
          },
          {
            "shade": "300",
            "hex": "#78C2AE"
          },
          {
            "shade": "500",
            "hex": "#2F8A72"
          },
          {
            "shade": "700",
            "hex": "#216A56"
          },
          {
            "shade": "900",
            "hex": "#164A3D"
          }
        ]
      }
    ],
    "semantic": {
      "success": {
        "name": "Verde Confirmação",
        "hex": "#2D8F63",
        "rgb": "45, 143, 99",
        "cmyk": "81, 18, 67, 5"
      },
      "error": {
        "name": "Vermelho Chapa",
        "hex": "#B44632",
        "rgb": "180, 70, 50",
        "cmyk": "17, 81, 81, 6"
      },
      "warning": {
        "name": "Amarelo Rodízio",
        "hex": "#E0B11E",
        "rgb": "224, 177, 30",
        "cmyk": "8, 30, 97, 3"
      },
      "info": {
        "name": "Verde Informação",
        "hex": "#2B7F73",
        "rgb": "43, 127, 115",
        "cmyk": "88, 28, 54, 11"
      }
    },
    "dataViz": [
      {
        "name": "Caraca Verde",
        "hex": "#006B60",
        "rgb": "0, 107, 96",
        "cmyk": "100, 28, 56, 21"
      },
      {
        "name": "Surpresa Amarela",
        "hex": "#D5A41D",
        "rgb": "213, 164, 29",
        "cmyk": "10, 34, 96, 7"
      },
      {
        "name": "Petisco Terracota",
        "hex": "#A85A31",
        "rgb": "168, 90, 49",
        "cmyk": "20, 66, 83, 10"
      },
      {
        "name": "Areia de Guardanapo",
        "hex": "#E8D5B5",
        "rgb": "232, 213, 181",
        "cmyk": "8, 13, 27, 0"
      },
      {
        "name": "Folha de Varanda",
        "hex": "#2F8A72",
        "rgb": "47, 138, 114",
        "cmyk": "82, 23, 57, 7"
      }
    ]
  },
  "typography": {
    "marketing": {
      "name": "Yellowtail",
      "usage": "Assinatura de marca, gestos visuais e chamadas que pedem calor humano e reconhecimento imediato do nome.",
      "weights": [
        "Regular"
      ],
      "fallbackFont": "Grand Hotel",
      "textTransform": "none",
      "category": "Script",
      "antiBlandingRationale": "Impede que o Caraca! vire mais um bar com tipografia neutra. O gesto caligráfico dá rosto humano à marca."
    },
    "ui": {
      "name": "Montserrat",
      "usage": "Textos de cardápio, rede social, sinalização complementar e UI do brandbook. É limpa, popular e direta.",
      "weights": [
        "Regular",
        "Medium",
        "SemiBold",
        "Bold"
      ],
      "fallbackFont": "Inter",
      "textTransform": "none",
      "category": "Sans-Serif",
      "antiBlandingRationale": "Mantém legibilidade e praticidade sem esfriar a marca. Funciona bem em promoções, preços e informação objetiva."
    },
    "monospace": {
      "name": "IBM Plex Mono",
      "usage": "Horários, códigos internos, price strips, notas técnicas e overlays utilitários em peças digitais.",
      "weights": [
        "Regular",
        "Medium"
      ],
      "fallbackFont": "Roboto Mono",
      "category": "Monospace",
      "antiBlandingRationale": "Cria contraste funcional com o lettering manual e ajuda a organizar informação sem parecer burocrático."
    },
    "primary": {
      "name": "Barlow Condensed",
      "usage": "Chamadas promocionais, combos, títulos de destaque e artes de oferta com energia de rua e leitura rápida.",
      "weights": [
        "Bold",
        "ExtraBold"
      ],
      "fallbackFont": "Oswald",
      "textTransform": "uppercase",
      "category": "Display",
      "antiBlandingRationale": "Dá impacto popular e ajuda a marca a gritar promoções com personalidade, sem recorrer a soluções genéricas de panfleto."
    },
    "secondary": {
      "name": "Inter",
      "usage": "Corpo de texto mais neutro, regras, descrições curtas e microcopy de apoio.",
      "weights": [
        "Regular",
        "Medium",
        "SemiBold"
      ],
      "fallbackFont": "Open Sans",
      "textTransform": "none",
      "category": "Sans-Serif",
      "antiBlandingRationale": "Equilibra o sistema e garante leitura confortável nas partes menos expressivas."
    }
  },
  "typographyScale": [
    {
      "name": "Display",
      "fontRole": "marketing",
      "size": "64px",
      "lineHeight": "70px",
      "fontWeight": "400",
      "usage": "Assinatura Caraca! Bar em fachada, capa e hero pieces"
    },
    {
      "name": "H1",
      "fontRole": "primary",
      "size": "46px",
      "lineHeight": "50px",
      "fontWeight": "800",
      "letterSpacing": "0.01em",
      "usage": "Grandes chamadas promocionais e nomes de campanha"
    },
    {
      "name": "H2",
      "fontRole": "primary",
      "size": "34px",
      "lineHeight": "38px",
      "fontWeight": "800",
      "letterSpacing": "0.02em",
      "usage": "Categorias como DRINKS, LANCHES, PRATOS e PORÇÕES"
    },
    {
      "name": "H3",
      "fontRole": "ui",
      "size": "24px",
      "lineHeight": "30px",
      "fontWeight": "700",
      "usage": "Nomes de pratos, burgers e drinks"
    },
    {
      "name": "H4",
      "fontRole": "ui",
      "size": "18px",
      "lineHeight": "24px",
      "fontWeight": "600",
      "usage": "Subtítulos, caixas de informação e chamadas de cardápio"
    },
    {
      "name": "Body Large",
      "fontRole": "secondary",
      "size": "16px",
      "lineHeight": "24px",
      "fontWeight": "400",
      "usage": "Descrições curtas e textos de apoio no cardápio"
    },
    {
      "name": "Body",
      "fontRole": "secondary",
      "size": "14px",
      "lineHeight": "22px",
      "fontWeight": "400",
      "usage": "Textos corridos, legendas e explicações institucionais"
    },
    {
      "name": "Body Small",
      "fontRole": "secondary",
      "size": "12px",
      "lineHeight": "18px",
      "fontWeight": "400",
      "usage": "Informações utilitárias, observações e rodapés"
    },
    {
      "name": "Caption",
      "fontRole": "ui",
      "size": "11px",
      "lineHeight": "16px",
      "fontWeight": "500",
      "usage": "Etiquetas, chips, labels de destaque e categorias auxiliares"
    },
    {
      "name": "Overline",
      "fontRole": "monospace",
      "size": "10px",
      "lineHeight": "14px",
      "fontWeight": "500",
      "letterSpacing": "0.14em",
      "usage": "Códigos, horários, IDs de peça e pequenos marcadores"
    },
    {
      "name": "Preço",
      "fontRole": "primary",
      "size": "22px",
      "lineHeight": "24px",
      "fontWeight": "800",
      "usage": "Preços e chamadas curtas em Amarelo Surpresa ou Terracota Petisco"
    }
  ],
  "designTokens": {
    "spacing": [
      "4px — micro",
      "8px — small",
      "12px — base",
      "16px — medium",
      "24px — large",
      "32px — xlarge",
      "48px — 2xlarge",
      "64px — 3xlarge",
      "96px — 4xlarge",
      "128px — 5xlarge"
    ],
    "borderRadii": [
      "0px — sharp (tags)",
      "4px — subtle (inputs)",
      "8px — default (cards, botões)",
      "12px — medium (cards sociais)",
      "16px — large (containers)",
      "999px — pill (badges)"
    ],
    "shadows": [
      "0 1px 2px rgba(30,58,47,0.05) — subtle",
      "0 2px 8px rgba(30,58,47,0.08) — card",
      "0 4px 16px rgba(30,58,47,0.12) — elevated",
      "0 8px 32px rgba(30,58,47,0.18) — floating"
    ],
    "breakpoints": [
      "375px — mobile",
      "768px — tablet",
      "1024px — desktop",
      "1440px — wide"
    ],
    "grid": "12 colunas, gutter 16px mobile / 24px desktop. Max-width 1200px."
  },
  "keyVisual": {
    "elements": [
      "Selo circular verde com lettering amarelo como ativo principal de reconhecimento",
      "Cantos tropicais controlados com folhas largas e recortes orgânicos",
      "Blocos promocionais com headline condensada e fundo sólido forte",
      "Tucano simplificado como personagem de apoio, nunca protagonista absoluto",
      "Azulejo, madeira, metal e textura de bar urbano como base material",
      "Produto e gente real como parte da identidade, não apenas fotografia funcional"
    ],
    "photographyStyle": "Fotografia de bar em operação: copos gelados, comida servida, mãos, brindes, gente real e pontos do ambiente. A luz é quente, urbana e convidativa — entre fim de tarde e noite viva. Priorizar close de produto e cenas espontâneas em vez de produção excessivamente editorial.",
    "iconography": "Ícones outline 2px em linguagem simples e amigável, frequentemente dentro de círculos ou medalhões. Funcionam bem para highlights, stories e sinalizações rápidas.",
    "illustrations": "Ilustração tropical simplificada com traço limpo e leitura popular. Menos gravura densa, mais linguagem gráfica aplicável a posts, adesivos, destaques e murais. O tucano e as folhas entram como apoio, com economia.",
    "marketingArchitecture": "1) selo/assinatura da marca; 2) headline curta em Barlow Condensed; 3) produto ou momento social como protagonista; 4) apoio visual por cantos botânicos, ícones circulares ou blocos de cor. A comunicação deve parecer viva e direta.",
    "compositionPhilosophy": "CENTRO CLARO, APOIO NAS BORDAS. O sistema abandona excesso ornamental contínuo e adota presença focal: logo, produto ou frase no centro; folhas, ícones e textura como moldura de apoio. A marca deve parecer organizada, não sufocada.",
    "mascots": [
      {
        "name": "Tucano de Apoio",
        "description": "Tucano simplificado em traço gráfico, usado como acento promocional e elemento simpático em peças específicas.",
        "personality": "Curioso, caloroso e ligeiramente irreverente. Ajuda a marca a sorrir sem virar infantil.",
        "usageGuidelines": [
          "Usar em promoções, destaques, sinalização e peças sociais específicas",
          "Preferir enquadramento de perfil ou 3/4 com leitura imediata",
          "Nunca competir com o logo principal",
          "Evitar excesso de detalhe ou tratamento hiper-realista"
        ]
      }
    ],
    "symbols": [
      "Selo circular da marca",
      "Ponto de exclamação como energia verbal, não fetiche gráfico",
      "Ícone de copo ou brinde como metáfora de encontro"
    ],
    "patterns": [
      "Padrão Canto Tropical",
      "Padrão Azulejo de Boteco",
      "Padrão Medalhões de Highlights",
      "Padrão Grade de Oferta"
    ],
    "structuredPatterns": [
      {
        "name": "Padrão Canto Tropical",
        "description": "Folhas e recortes orgânicos aplicados apenas nas margens.",
        "composition": "Elementos botânicos amplos em 2 ou 3 cantos, preservando centro limpo para headline ou produto.",
        "usage": "Posts institucionais, cardápio, stories e peças de ambientação.",
        "density": "moderado",
        "background": "Areia de Guardanapo (#E8D5B5) ou Verde Caraca (#006B60)"
      },
      {
        "name": "Padrão Azulejo de Boteco",
        "description": "Geometria inspirada em balcão, revestimento e ritmo urbano brasileiro.",
        "composition": "Módulos simples e repetíveis com base ortogonal, sem excessos coloniais decorativos.",
        "usage": "Cardápios, paredes, embalagens secundárias e social backgrounds.",
        "density": "moderado",
        "background": "Verde Caraca (#006B60) com Areia de Guardanapo (#E8D5B5)"
      },
      {
        "name": "Padrão Medalhões de Highlights",
        "description": "Sistema de círculos e anéis para categorias como Drinks, Clientes, Lanches, Pratos e Porções.",
        "composition": "Anéis, ícones e rótulos curtos com ritmo uniforme.",
        "usage": "Highlights, destaques do Instagram, cards rápidos e menus digitais.",
        "density": "espaçado",
        "background": "Verde Caraca (#006B60) ou Amarelo Surpresa (#D5A41D)"
      },
      {
        "name": "Padrão Grade de Oferta",
        "description": "Blocos de oferta com headlines condensadas e áreas dedicadas a preço ou benefício.",
        "composition": "Grid simples de 2 a 4 módulos com headline, apoio e produto.",
        "usage": "Promoções, combos, rodízio, banners e posts de campanha.",
        "density": "moderado",
        "background": "Misto entre Verde Caraca, Areia de Guardanapo e Terracota Petisco"
      }
    ],
    "flora": [
      "Costela-de-Adão",
      "Folhas largas de varanda",
      "Limão",
      "Pimenta",
      "Ramos simplificados de apoio"
    ],
    "fauna": [
      "Tucano simplificado como apoio"
    ],
    "objects": [
      "Copo Lagoinha",
      "Espeto",
      "Hambúrguer/lanche como produto-herói",
      "Azulejo de balcão",
      "Mesa compartilhada"
    ]
  },
  "applications": [
    {
      "type": "Cardápio Físico",
      "description": "Cardápio em base areia com selo verde-amarelo, categorias fortes e apoio tropical nas bordas.",
      "imagePlaceholder": "https://placehold.co/800x600/E8D5B5/006B60?text=Cardapio+Caraca",
      "imageKey": "brand_collateral",
      "dimensions": "A4 ou 210×297mm com versões de mesa e prancheta",
      "materialSpecs": "Papel offset encorpado ou reciclato premium 240g. Possível capa em kraft claro ou cartão fosco.",
      "layoutGuidelines": "Logo no topo, categorias em blocos claros, preços com contraste alto. Usar apoio tropical nos cantos e áreas de respiro bem definidas.",
      "typographyHierarchy": "Logo em Yellowtail, categorias em Barlow Condensed, itens em Montserrat, descrições em Inter e preços em Barlow Condensed/Terracota Petisco.",
      "artDirection": "Menos floresta total, mais sistema limpo com calor de bar urbano.",
      "substrates": [
        "Papel offset 240g",
        "Reciclato premium",
        "Kraft claro opcional"
      ]
    },
    {
      "type": "Instagram Feed — Produto & Promo",
      "description": "Sistema que alterna close de produto, clientes, ambiente e promoções curtas com identidade reconhecível.",
      "imagePlaceholder": "https://placehold.co/1080x1080/006B60/D5A41D?text=Feed+Caraca",
      "imageKey": "social_post_square",
      "dimensions": "1080×1080px, 1080×1350px e 1080×1920px",
      "materialSpecs": "Digital em sRGB, JPG 85-90% para feed e PNG quando houver sobreposição gráfica.",
      "layoutGuidelines": "Intercalar 60% produto/ambiente real, 25% clientes e 15% promoções. Nas promos, usar headline curta, preço/benefício claro e selo da marca visível.",
      "typographyHierarchy": "Headline em Barlow Condensed, apoio em Montserrat, assinatura em Yellowtail quando houver necessidade de reforço de marca.",
      "artDirection": "Produto ou momento humano sempre em foco. Cantos tropicais e medalhões só entram como apoio.",
      "substrates": [
        "Digital — sRGB"
      ]
    },
    {
      "type": "Destaques do Instagram",
      "description": "Sistema de highlights circulares para Drinks, Clientes, Lanches, Pratos, Porções e Nosso bar.",
      "imagePlaceholder": "https://placehold.co/800x600/006B60/D5A41D?text=Highlights+Caraca",
      "imageKey": "social_story",
      "dimensions": "Capa 1080×1920px adaptada para recorte circular",
      "materialSpecs": "Digital vetorial com export em PNG @2x e SVG mestre.",
      "layoutGuidelines": "Manter consistência absoluta de espessura, alinhamento e escala entre ícones.",
      "typographyHierarchy": "Preferir ícone puro; quando houver texto, usar Montserrat SemiBold.",
      "artDirection": "Círculo verde, ícone amarelo, linguagem minimalista e simpática.",
      "substrates": [
        "Digital — SVG + PNG"
      ]
    },
    {
      "type": "Fachada e Sinalização",
      "description": "Fachada com selo/assinatura de alta leitura e sinalização interna que reforça encontro e brasilidade urbana.",
      "imagePlaceholder": "https://placehold.co/800x600/0E4038/D5A41D?text=Fachada+Caraca",
      "imageKey": "outdoor_billboard",
      "dimensions": "Letreiro principal 2200×700mm; placas internas modulares 500×700mm",
      "materialSpecs": "Acrílico, chapa metálica pintada, adesivo fosco e pintura mural com acabamento matte.",
      "layoutGuidelines": "Priorizar leitura à distância. O selo pode coexistir com wordmark, mas sem poluição adicional.",
      "typographyHierarchy": "Logo em destaque, mensagens secundárias em Barlow Condensed ou Montserrat.",
      "artDirection": "A rua vê a energia verde-amarela; o interior confirma o clima com textura, luz quente e apoio gráfico controlado.",
      "substrates": [
        "Acrílico",
        "Chapa metálica",
        "Adesivo fosco",
        "Pintura mural"
      ]
    },
    {
      "type": "Delivery e Sacola",
      "description": "Sacolas e embalagens com sistema enxuto: selo forte, bloco de cor, padrão de apoio e frases curtas.",
      "imagePlaceholder": "https://placehold.co/800x600/E8D5B5/006B60?text=Delivery+Caraca",
      "imageKey": "food_container",
      "dimensions": "Sacola P/M/G e adesivos 60mm-90mm",
      "materialSpecs": "Kraft claro, adesivo fosco, impressão flexográfica de 2 a 3 cores sólidas.",
      "layoutGuidelines": "Evitar excesso de informação. Logo, frase curta e um padrão consistente bastam.",
      "typographyHierarchy": "Assinatura em destaque, apoio em Montserrat e headlines pontuais em Barlow Condensed.",
      "artDirection": "Mais reconhecimento e portabilidade, menos ornamentação densa.",
      "substrates": [
        "Kraft claro",
        "Adesivo fosco",
        "Flexografia 2-3 cores"
      ]
    }
  ],
  "socialMediaGuidelines": {
    "platforms": [
      {
        "platform": "Instagram",
        "primaryFormats": "Feed 1080×1080 e 1080×1350, Stories/Reels 1080×1920, Highlights circulares",
        "tone": "Caloroso, direto e visual. A legenda entra para completar o desejo, não para explicar demais.",
        "contentPillars": [
          "Drinks",
          "Clientes",
          "Lanches",
          "Pratos",
          "Porções",
          "Nosso bar"
        ],
        "frequency": "Feed 4-6x por semana. Stories diários. Reels 2-4x por semana.",
        "doList": [
          "Manter alternância entre produto, ambiente e gente",
          "Usar o sistema de highlights como arquitetura fixa",
          "Fazer promoções com headline curta e leitura rápida",
          "Mostrar a casa viva e não apenas peças estáticas"
        ],
        "dontList": [
          "Não lotar o feed com arte sem foto real",
          "Não descaracterizar o verde + amarelo",
          "Não usar linguagem de restaurante formal",
          "Não exagerar no tropical a ponto de virar parque temático"
        ],
        "examplePost": "Caraca, essa mesa aqui tá pedindo tua turma. Drink gelado, porção saindo e aquele clima que faz tu ficar mais um pouco. #caracabar #vemprobem"
      },
      {
        "platform": "WhatsApp Business",
        "primaryFormats": "Texto curto, imagem quadrada, card vertical e status 1080×1920",
        "tone": "Próximo, útil e rápido. Fala como o bar que já te conhece.",
        "contentPillars": [
          "Reserva",
          "Promo do dia",
          "Rodízio",
          "Novidade do cardápio"
        ],
        "frequency": "Até 3 disparos por semana; atendimento contínuo em horário operacional.",
        "doList": [
          "Ser objetivo",
          "Convidar com simpatia",
          "Resolver rápido reserva e dúvida"
        ],
        "dontList": [
          "Não usar texto longo",
          "Não parecer SAC robotizado",
          "Não disparar em excesso"
        ],
        "examplePost": "Oi! Hoje tem rodada boa de porções e mesa livre mais tarde. Quer que eu já separe pra vocês?"
      },
      {
        "platform": "TikTok",
        "primaryFormats": "Vídeos verticais 1080×1920 entre 10 e 45 segundos",
        "tone": "Mais cru, divertido e reativo que o Instagram. Deve parecer noite acontecendo.",
        "contentPillars": [
          "Montagem de drinks",
          "Saída de pratos e porções",
          "Reação de clientes",
          "Bastidor do bar"
        ],
        "frequency": "3-5 vídeos por semana",
        "doList": [
          "Filmar mão, fumaça, gelo, crocância e brinde",
          "Mostrar movimento real da casa",
          "Editar com ritmo"
        ],
        "dontList": [
          "Não forçar trend incompatível",
          "Não roteirizar demais",
          "Não polir a ponto de perder verdade"
        ],
        "examplePost": "POV: era só um drink rápido e tu já tá pedindo porção, chamando amigo e ficando até mais tarde."
      }
    ],
    "globalHashtagStrategy": "Base fixa: #caracabar #vemprobem. Apoio rotativo por categoria: #drinks #porcoes #lanches #pratos #nossoBar #londrina.",
    "brandVoiceAdaptation": "A voz é sempre brasileira, calorosa e convidativa. O Instagram organiza desejo, o WhatsApp resolve, e o TikTok mostra a vida acontecendo. Em todos os canais a marca deve soar presente, nunca genérica."
  },
  "productionGuidelines": {
    "fileNamingConvention": "caraca_[asset]_[variante]_[cor]_[tamanho]_[formato]. Ex: caraca_logo_selo_verde-amarelo_800x300_rgb.png, caraca_highlight_drinks_svg.svg, caraca_post_promocao_combo_1080x1350_rgb.png",
    "handoffChecklist": [
      "Confirmar versão oficial do selo e do wordmark",
      "Converter fontes em curvas (Create Outlines)",
      "Expandir traços (Outline Stroke)",
      "Exportar highlights em SVG e PNG @2x",
      "Garantir contraste mínimo entre Verde Caraca e Amarelo Surpresa",
      "Testar logo sobre foto real e fundo sólido",
      "Separar arquivos por /logo /social /print /signage /delivery",
      "Revisar sangria e margem de segurança nas peças impressas",
      "Checar legibilidade do lettering em bordado e adesivo pequeno",
      "Validar perfis de cor CMYK e sRGB conforme saída",
      "Incluir mockups de fachada, feed e cardápio",
      "Entregar biblioteca de ícones de highlights com nomes consistentes"
    ],
    "printSpecs": {
      "colorProfile": "CMYK — Fogra39 ou equivalente definido pela gráfica",
      "resolution": "300 DPI para raster; vetores sempre que possível",
      "bleed": "3mm a 5mm em peças full-bleed",
      "safeMargin": "3mm a 5mm para headline, preço e assinatura",
      "notes": "O Amarelo Surpresa perde força em substratos escuros ou kraft sem base clara. Em materiais críticos, prever branco de apoio ou ajustar contraste."
    },
    "digitalSpecs": {
      "colorSpace": "sRGB",
      "exportScales": [
        "1x",
        "2x",
        "3x"
      ],
      "formats": [
        "SVG",
        "PNG",
        "JPG",
        "PDF/X-1a",
        "AI/EPS"
      ],
      "compressionGuidelines": "Feed JPG 85-90%; stories JPG 80-85%; SVG minificado para ícones e assets vetoriais.",
      "notes": "Preservar arquivos mestres das artes promocionais com camadas editáveis e manter ícones sociais como biblioteca vetorial única."
    },
    "deliverables": [
      {
        "asset": "Logo principal + selo",
        "formats": [
          "SVG",
          "PNG @2x",
          "AI",
          "EPS"
        ],
        "specs": "Versões positiva, negativa, monocromática e aplicação sobre foto"
      },
      {
        "asset": "Kit de highlights",
        "formats": [
          "SVG",
          "PNG @2x"
        ],
        "specs": "Drinks, Clientes, Lanches, Pratos, Porções, Nosso bar"
      },
      {
        "asset": "Templates de feed e stories",
        "formats": [
          "Figma",
          "PNG",
          "PSD"
        ],
        "specs": "Produto, promo, institucional e agenda"
      },
      {
        "asset": "Cardápio e sinalização",
        "formats": [
          "PDF",
          "AI",
          "INDD/Figma"
        ],
        "specs": "Menu principal, placas internas e mural"
      },
      {
        "asset": "Delivery pack",
        "formats": [
          "AI",
          "PDF",
          "PNG"
        ],
        "specs": "Sacola, adesivo e selo reduzido"
      }
    ],
    "productionMethods": [
      {
        "method": "Flexografia",
        "substrate": "Sacolas, adesivos e embalagens delivery",
        "guidelines": [
          "Limitar a 2-3 cores sólidas",
          "Preservar áreas de respiro do selo",
          "Traço mínimo de 0.5pt nos ícones"
        ],
        "restrictions": [
          "Evitar gradiente",
          "Evitar texto negativo muito pequeno",
          "Não usar detalhes finos no lettering em escala reduzida"
        ]
      },
      {
        "method": "Serigrafia / Silk-screen",
        "substrate": "Uniformes, ecobags e aventais",
        "guidelines": [
          "Separar Verde Caraca e Amarelo Surpresa em chapas distintas",
          "Usar base clara quando necessário",
          "Preferir selo e headlines de alto contraste"
        ],
        "restrictions": [
          "Sem gradientes",
          "Sem lettering muito fino",
          "Máximo de 4 cores por aplicação"
        ]
      },
      {
        "method": "Bordado",
        "substrate": "Bonés, polos e aventais",
        "guidelines": [
          "Usar versão simplificada do selo",
          "Reforçar espessura do lettering",
          "Tamanho mínimo de 5cm de largura"
        ],
        "restrictions": [
          "Não usar tagline em escala mínima",
          "Não usar ícones com detalhe excessivo",
          "Máximo de 5-6 cores de fio"
        ]
      },
      {
        "method": "Impressão Digital / Plotagem",
        "substrate": "Murais, placas e ambientação",
        "guidelines": [
          "Trabalhar em áreas amplas de cor sólida",
          "Garantir leitura à distância",
          "Usar acabamento fosco para preservar calor material"
        ],
        "restrictions": [
          "Evitar brilho excessivo",
          "Evitar excesso de elementos no mural principal"
        ]
      }
    ]
  },
  "imageGenerationBriefing": {
    "visualStyle": "Tropical urbano brasileiro com mistura de fotografia real de bar, design promocional popular bem resolvido e apoio gráfico controlado. Menos gravura densa, mais sistema reconhecível e vivo.",
    "colorMood": "Predominância de Verde Caraca (#006B60) e Amarelo Surpresa (#D5A41D), com apoio de Areia de Guardanapo (#E8D5B5), Terracota Petisco (#A85A31) e Folha de Varanda (#2F8A72). Sensação quente, convidativa e noturna sem perder frescor.",
    "compositionNotes": "Organizar a composição a partir de um foco claro: produto, logo ou momento humano. As bordas recebem apoio tropical ou textura; o centro mantém leitura. Alternar peças com mais foto e peças com mais headline, mas sempre preservando reconhecimento imediato do sistema.",
    "moodKeywords": [
      "boteco",
      "tropical urbano",
      "calor humano",
      "bar vivo",
      "promocional com personalidade",
      "verde e amarelo",
      "encontro",
      "produto apetitoso",
      "brasilidade cotidiana"
    ],
    "artisticReferences": "Campanhas populares brasileiras bem resolvidas, food photography de bar contemporâneo, sinalização urbana e sistemas sociais de marcas locais com forte presença real.",
    "avoidElements": "Estética de pub inglês, industrial hipster, fine dining, neon de balada genérica, resort tropical, excesso de ilustração botânica densa, minimalismo frio, preto chapado dominante.",
    "logoStyleGuide": "Usar selo/assinatura como ponto principal de reconhecimento. O gesto do nome precisa parecer humano, espontâneo e legível, sempre ancorado na relação Verde Caraca + Amarelo Surpresa.",
    "photographyMood": "Produto em primeiro plano, copos gelados, luz quente, fundo de bar real, gente presente quando couber, madeira e azulejo como suporte. Evitar sets artificiais demais.",
    "patternStyle": "Sistema de apoio composto por canto tropical, azulejo de boteco, medalhões de highlights e grades simples de promoção. Tudo precisa ser reproduzível em social, signage e cardápio.",
    "marketingVisualLanguage": "Headline curta, logo visível, produto desejável e apoio visual mínimo necessário. A marca deve parecer em movimento e em operação, não como moodboard conceitual.",
    "negativePrompt": "NO pub aesthetic, NO industrial hipster bar, NO fine dining plating, NO resort tropical clichés, NO overdecorated botanical engraving, NO cold corporate minimalism, NO neon nightclub visuals, NO black-dominant background, NO generic stock imagery"
  }
} as unknown as BrandbookData;
