import type { BrandbookData } from "./types";
import { downloadTextFile as downloadTextFileShared } from "./browserDownload";

export function exportCSSTokens(data: BrandbookData): string {
  const slug = data.brandName.toLowerCase().replace(/[^a-z0-9]/g, "-").replace(/-+/g, "-");
  const lines: string[] = [
    `/* ============================================================`,
    ` * Design Tokens — ${data.brandName}`,
    ` * Generated by Brandbook Builder`,
    ` * ============================================================ */`,
    "",
    `:root {`,
    `  /* ─── Colors: Primary ─── */`,
  ];

  data.colors.primary.forEach((c, i) => {
    const varName = `--${slug}-color-primary-${i + 1}`;
    const pantoneStr = c.pantone ? ` | ${c.pantone}` : "";
    const comment = c.usage ? `${c.name}${pantoneStr} — ${c.usage}` : `${c.name}${pantoneStr}`;
    lines.push(`  ${varName}: ${c.hex}; /* ${comment} */`);
  });

  lines.push("", `  /* ─── Colors: Secondary ─── */`);
  data.colors.secondary.forEach((c, i) => {
    const pantoneStr = c.pantone ? ` | ${c.pantone}` : "";
    const comment = c.usage ? `${c.name}${pantoneStr} — ${c.usage}` : `${c.name}${pantoneStr}`;
    lines.push(`  --${slug}-color-secondary-${i + 1}: ${c.hex}; /* ${comment} */`);
  });

  if (data.colors.semantic) {
    lines.push("", `  /* ─── Colors: Semantic ─── */`);
    lines.push(`  --${slug}-color-success: ${data.colors.semantic.success?.hex ?? "#22c55e"};`);
    lines.push(`  --${slug}-color-error: ${data.colors.semantic.error?.hex ?? "#ef4444"};`);
    lines.push(`  --${slug}-color-warning: ${data.colors.semantic.warning?.hex ?? "#f59e0b"};`);
    lines.push(`  --${slug}-color-info: ${data.colors.semantic.info?.hex ?? "#3b82f6"};`);
  }

  lines.push("", `  /* ─── Typography Families ─── */`);
  if (data.typography?.marketing) {
    const fb = data.typography.marketing.fallbackFont ? `, '${data.typography.marketing.fallbackFont}'` : "";
    lines.push(`  --${slug}-font-marketing: '${data.typography.marketing.name}'${fb}, sans-serif;`);
  }
  if (data.typography?.ui) {
    const fb = data.typography.ui.fallbackFont ? `, '${data.typography.ui.fallbackFont}'` : "";
    lines.push(`  --${slug}-font-ui: '${data.typography.ui.name}'${fb}, sans-serif;`);
  }
  if (data.typography?.monospace) {
    const fb = data.typography.monospace.fallbackFont ? `, '${data.typography.monospace.fallbackFont}'` : "";
    lines.push(`  --${slug}-font-mono: '${data.typography.monospace.name}'${fb}, monospace;`);
  }
  if (data.typography?.primary) {
    const fb = data.typography.primary.fallbackFont ? `, '${data.typography.primary.fallbackFont}'` : "";
    lines.push(`  --${slug}-font-primary: '${data.typography.primary.name}'${fb}, sans-serif;`);
  }
  if (data.typography?.secondary) {
    const fb = data.typography.secondary.fallbackFont ? `, '${data.typography.secondary.fallbackFont}'` : "";
    lines.push(`  --${slug}-font-secondary: '${data.typography.secondary.name}'${fb}, sans-serif;`);
  }

  lines.push("", `  /* ─── Typography Scale ─── */`);
  (data.typographyScale ?? []).forEach((t) => {
    const key = t.name.toLowerCase().replace(/\s+/g, "-");
    lines.push(`  --${slug}-text-${key}-size: ${t.size};`);
    lines.push(`  --${slug}-text-${key}-line-height: ${t.lineHeight};`);
    lines.push(`  --${slug}-text-${key}-weight: ${t.fontWeight};`);
    if (t.letterSpacing) lines.push(`  --${slug}-text-${key}-tracking: ${t.letterSpacing};`);
  });

  lines.push("", `  /* ─── Spacing ─── */`);
  (data.designTokens?.spacing ?? []).forEach((s, i) => {
    const value = s.match(/^(\d+(?:\.\d+)?(?:px|rem|em))/)?.[1] || s.split(" ")[0];
    lines.push(`  --${slug}-space-${i + 1}: ${value}; /* ${s} */`);
  });

  lines.push("", `  /* ─── Border Radius ─── */`);
  (data.designTokens?.borderRadii ?? []).forEach((r, i) => {
    const value = r.match(/^(\d+(?:\.\d+)?(?:px|rem|em))/)?.[1] || r.split(" ")[0];
    lines.push(`  --${slug}-radius-${i + 1}: ${value}; /* ${r} */`);
  });

  if (data.designTokens?.shadows && data.designTokens.shadows.length > 0) {
    lines.push("", `  /* ─── Shadows ─── */`);
    data.designTokens.shadows.forEach((s, i) => {
      const value = s.match(/^([^—–]+)/)?.[1]?.trim() || s.split(" — ")[0];
      lines.push(`  --${slug}-shadow-${i + 1}: ${value}; /* ${s} */`);
    });
  }

  if (data.designTokens?.breakpoints && data.designTokens.breakpoints.length > 0) {
    lines.push("", `  /* ─── Breakpoints ─── */`);
    data.designTokens.breakpoints.forEach((b, i) => {
      const value = b.match(/^(\d+(?:\.\d+)?(?:px|rem|em))/)?.[1] || b.split(" ")[0];
      lines.push(`  --${slug}-breakpoint-${i + 1}: ${value}; /* ${b} */`);
    });
  }

  lines.push("}");
  return lines.join("\n");
}

export function exportW3CTokens(data: BrandbookData): string {
  const tokens: Record<string, unknown> = {
    color: {
      primary: Object.fromEntries(
        data.colors.primary.map((c, i) => [
          `${i + 1}`,
          { $value: c.hex, $type: "color", $description: c.name },
        ])
      ),
      secondary: Object.fromEntries(
        data.colors.secondary.map((c, i) => [
          `${i + 1}`,
          { $value: c.hex, $type: "color", $description: c.name },
        ])
      ),
      ...(data.colors.semantic ? { semantic: {
        success: { $value: data.colors.semantic.success?.hex, $type: "color" },
        error: { $value: data.colors.semantic.error?.hex, $type: "color" },
        warning: { $value: data.colors.semantic.warning?.hex, $type: "color" },
        info: { $value: data.colors.semantic.info?.hex, $type: "color" },
      }} : {}),
    },
    typography: {
      family: {
        ...(data.typography?.marketing ? { marketing: { $value: `'${data.typography.marketing.name}'${data.typography.marketing.fallbackFont ? `, '${data.typography.marketing.fallbackFont}'` : ""}, sans-serif`, $type: "fontFamily" } } : {}),
        ...(data.typography?.ui ? { ui: { $value: `'${data.typography.ui.name}'${data.typography.ui.fallbackFont ? `, '${data.typography.ui.fallbackFont}'` : ""}, sans-serif`, $type: "fontFamily" } } : {}),
        ...(data.typography?.monospace ? { mono: { $value: `'${data.typography.monospace.name}'${data.typography.monospace.fallbackFont ? `, '${data.typography.monospace.fallbackFont}'` : ""}, monospace`, $type: "fontFamily" } } : {}),
        ...(data.typography?.primary ? { primary: { $value: `'${data.typography.primary.name}'${data.typography.primary.fallbackFont ? `, '${data.typography.primary.fallbackFont}'` : ""}, sans-serif`, $type: "fontFamily" } } : {}),
        ...(data.typography?.secondary ? { secondary: { $value: `'${data.typography.secondary.name}'${data.typography.secondary.fallbackFont ? `, '${data.typography.secondary.fallbackFont}'` : ""}, sans-serif`, $type: "fontFamily" } } : {}),
      },
      scale: Object.fromEntries(
        (data.typographyScale ?? []).map((t) => [
          t.name.toLowerCase().replace(/\s+/g, "-"),
          {
            fontSize: { $value: t.size, $type: "dimension" },
            lineHeight: { $value: t.lineHeight, $type: "dimension" },
            fontWeight: { $value: t.fontWeight, $type: "fontWeight" },
            ...(t.letterSpacing ? { letterSpacing: { $value: t.letterSpacing, $type: "dimension" } } : {}),
          },
        ])
      ),
    },
    spacing: Object.fromEntries(
      (data.designTokens?.spacing ?? []).map((s, i) => {
        const value = s.match(/^(\d+(?:\.\d+)?(?:px|rem|em))/)?.[1] || s.split(" ")[0];
        return [`scale-${i + 1}`, { $value: value, $type: "dimension", $description: s }];
      })
    ),
    borderRadius: Object.fromEntries(
      (data.designTokens?.borderRadii ?? []).map((r, i) => {
        const value = r.match(/^(\d+(?:\.\d+)?(?:px|rem|em))/)?.[1] || r.split(" ")[0];
        return [`scale-${i + 1}`, { $value: value, $type: "dimension", $description: r }];
      })
    ),
  };
  return JSON.stringify(tokens, null, 2);
}

export function exportTailwindConfig(data: BrandbookData): string {
  const indent = "          ";
  const colorLines: string[] = [];

  data.colors.primary.forEach((c, i) => colorLines.push(`${indent}"primary-${i + 1}": "${c.hex}",`));
  data.colors.secondary.forEach((c, i) => colorLines.push(`${indent}"secondary-${i + 1}": "${c.hex}",`));
  if (data.colors.semantic) {
    colorLines.push(`${indent}"success": "${data.colors.semantic.success?.hex ?? "#22c55e"}",`);
    colorLines.push(`${indent}"error": "${data.colors.semantic.error?.hex ?? "#ef4444"}",`);
    colorLines.push(`${indent}"warning": "${data.colors.semantic.warning?.hex ?? "#f59e0b"}",`);
    colorLines.push(`${indent}"info": "${data.colors.semantic.info?.hex ?? "#3b82f6"}",`);
  }

  const fontLines: string[] = [];
  if (data.typography?.marketing) {
    const fb = data.typography.marketing.fallbackFont ? `"'${data.typography.marketing.fallbackFont}'", ` : "";
    fontLines.push(`        marketing: ["'${data.typography.marketing.name}'", ${fb}"sans-serif"],`);
  }
  if (data.typography?.ui) {
    const fb = data.typography.ui.fallbackFont ? `"'${data.typography.ui.fallbackFont}'", ` : "";
    fontLines.push(`        ui: ["'${data.typography.ui.name}'", ${fb}"sans-serif"],`);
  }
  if (data.typography?.monospace) {
    const fb = data.typography.monospace.fallbackFont ? `"'${data.typography.monospace.fallbackFont}'", ` : "";
    fontLines.push(`        mono: ["'${data.typography.monospace.name}'", ${fb}"monospace"],`);
  }
  if (data.typography?.primary) {
    const fb = data.typography.primary.fallbackFont ? `"'${data.typography.primary.fallbackFont}'", ` : "";
    fontLines.push(`        primary: ["'${data.typography.primary.name}'", ${fb}"sans-serif"],`);
  }
  if (data.typography?.secondary) {
    const fb = data.typography.secondary.fallbackFont ? `"'${data.typography.secondary.fallbackFont}'", ` : "";
    fontLines.push(`        secondary: ["'${data.typography.secondary.name}'", ${fb}"sans-serif"],`);
  }

  const spacingObj = Object.fromEntries(
    (data.designTokens?.spacing ?? []).map((s, i) => {
      const value = s.match(/^(\d+(?:\.\d+)?(?:px|rem|em))/)?.[1] || s.split(" ")[0];
      return [`brand-${i + 1}`, value];
    })
  );

  return [
    "/** @type {import('tailwindcss').Config} */",
    `// Generated by Brandbook Builder — ${data.brandName}`,
    "module.exports = {",
    "  theme: {",
    "    extend: {",
    "      colors: {",
    "        brand: {",
    ...colorLines,
    "        },",
    "      },",
    "      fontFamily: {",
    ...fontLines,
    "      },",
    `      spacing: ${JSON.stringify(spacingObj, null, 8)},`,
    "    },",
    "  },",
    "};",
  ].join("\n");
}

export function downloadTextFile(content: string, filename: string, mimeType = "text/plain") {
  downloadTextFileShared(content, filename, mimeType);
}
